
--SCRIPT SOBRE LA ESTRATEGIA DE BACKUPS MEDIANTE EL USO DE SQL AGENT

--CREACION DE TRABAJOS DE PLAN DE BACKUPS

/***** COMANDO QUE SE COLOCO EN EL TRABAJO DE FULL BACKUP *****/
--			Realizar Backup COMPLETO
BACKUP DATABASE DB_Hospital
TO DISK = 'C:\backups\DB_Hospital_FULL_BASE.bak'
WITH INIT, COMPRESSION, STATS = 5;


/***** COMANDO QUE SE COLOCO EN EL TRABAJO DE DIFERENCIAL BACKUP *****/
--			Realizar Backup DIFERENCIAL
BACKUP DATABASE DB_Hospital
TO DISK = 'C:\backups\DB_Hospital_DIFFinserts.bak'
WITH DIFFERENTIAL, COMPRESSION, STATS = 5;


/***** COMANDO QUE SE COLOCO EN EL TRABAJO DE INCREMENTAL(LOG) BACKUP *****/
--			Realizar Backup INCREMENTAL(LOG)
BACKUP LOG DB_Hospital
TO DISK = 'C:\backups\DB_Hospital_LOG_001.trn'
WITH INIT, COMPRESSION, STATS = 5;
