
/*INSERCION DE DATOS A LA BASE POR MEDIO DE SQL_DATA_GENERATOR*/

--INSERCION DE DATOS DE INSTRUMENTOMEDICO 450 datos
BULK INSERT Inventario.InstrumentoMedico
FROM 'C:\bulk_data\InstrumentoMedico.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

--INSERCION DE DATOS DE ANALGESICO 500 datos
BULK INSERT Inventario.Analgesico
FROM 'C:\bulk_data\Analgesico.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

--INSERCION DE DATOS DE MEDICAMENTO 500 datos
BULK INSERT Inventario.Medicamento
FROM 'C:\bulk_data\Medicamento.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

--INSERCION DE DATOS DE BODEGA 600 datos
BULK INSERT Inventario.Bodega
FROM 'C:\bulk_data\Bodega.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

--INSERCION DE DATOS DE MEDICO 200 datos
BULK INSERT Clinica.Medico
FROM 'C:\bulk_data\Medico.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

-- INSERCION DE DATOS PACIENTE 850 datos
BULK INSERT Clinica.Paciente
FROM 'C:\bulk_data\Paciente.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

--INSERCION DE DATOS DE CITA 1000 datos
BULK INSERT Clinica.Cita 
FROM 'C:\bulk_data\Cita.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

select * from Clinica.Cita

-- INSERCION DE DATOS DE TRATAMIENTO 300 datos
BULK INSERT Clinica.Tratamiento
FROM 'C:\bulk_data\Tratamiento.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

-- INSERCION DE DATOS DE METODOPAGO 500 datos
BULK INSERT Contabilidad.MetodoPago
FROM 'C:\bulk_data\MetodoPago.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

-- INSERCION DE DATOS DE FACTURA
BULK INSERT Contabilidad.Factura
FROM 'C:\bulk_data\Factura.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

--INSERCION DE DATOS DE DEPARTAMENTO 200 datos (INSERTE DOS VECES)
BULK INSERT Administracion.Departamento
FROM 'C:\bulk_data\Departamento.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);

-- INSERCION DE DATOS DE DEPAXMED 200 datos
BULK INSERT Clinica.DepaXMed
FROM 'C:\bulk_data\DepaXMed.csv'
WITH(
	FIELDTERMINATOR = ',',
	ROWTERMINATOR = '\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
);
